### ISSUE TITLE
Can't open some XLSX files

### ISSUE THREAD

**Issue by pintaf** [tableflowhq/csv-import#219]
This library works with some XLSX files, but with others, it doesn't.

```
index.js:44810 Uncaught (in promise) TypeError: cell.trim is not a function
    at index.js:44810:110
    at Array.some (<anonymous>)
    at isNotBlankRow (index.js:44810:75)
    at Array.filter (<anonymous>)
    at index.js:44840:61
    at step (index.js:92:23)
    at Object.next (index.js:73:53)
    at index.js:66:71
    at new Promise (<anonymous>)
    at __awaiter (index.js:62:12)
```

Issue seems to be in the `isNotBlankRow` function.

Problematic file attached
[problematic excel.xlsx](https://github.com/tableflowhq/csv-import/files/14745874/problematic.excel.xlsx)

**Comment by ciminelli** [comment]
@pintaf thanks for the issue. This is fixed in version `1.0.11`
